[package]
name                 = "kernel"
version.workspace    = true
edition.workspace    = true
repository.workspace = true
license.workspace    = true
publish.workspace    = true

[lib]
name = "kernel_lib"

[dependencies]
log.workspace    = true
riscv.workspace  = true
sbi-rt.workspace = true
spin.workspace   = true

[lints]
workspace = true
