[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
# rustflags = ["-Clink-arg=-Tsrc/linker.ld", "-Cforce-frame-pointers=yes"]

[unstable]
bindeps            = true
build-std          = ["alloc", "compiler_builtins", "core"]
build-std-features = ["compiler-builtins-mem"]
json-target-spec   = true
